// dashboard/pages/workspace.js
// ==============================
// XPS Intelligence – Workspace / Centre Editor
//
// Features:
//   • Embedded browser preview (iframe)
//   • Live UI code editor with real-time preview
//   • Image / UI generation via LLM command
//   • Self-editing: modify any page's source live
//   • Parallel execution monitor
//   • Autonomous agent console

import React, { useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";

const API_URL =
  typeof window !== "undefined"
    ? process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"
    : "http://localhost:8000";

const INITIAL_HTML = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { margin:0; background:#000; color:#FFD700; font-family:system-ui,sans-serif; display:flex; align-items:center; justify-content:center; min-height:100vh; }
    .card { background:#111; border:1px solid #FFD700; border-radius:12px; padding:2rem; text-align:center; max-width:480px; }
    h1 { font-size:2rem; margin:0 0 0.5rem; }
    p  { color:#aaa; }
    button { background:#FFD700; color:#000; border:none; padding:0.6rem 1.5rem; border-radius:6px; font-size:1rem; cursor:pointer; margin-top:1rem; }
  </style>
</head>
<body>
  <div class="card">
    <h1>⚡ XPS UI Preview</h1>
    <p>Edit the HTML in the left panel to see live changes here.</p>
    <button onclick="this.textContent='✅ Clicked!'">Click Me</button>
  </div>
</body>
</html>`;

const PANEL_PRESETS = {
  browser: "browser",
  editor: "editor",
  split: "split",
};

export default function WorkspacePage() {
  const [mode, setMode] = useState("split");
  const [htmlCode, setHtmlCode] = useState(INITIAL_HTML);
  const [previewSrc, setPreviewSrc] = useState("https://example.com");
  const [browserUrl, setBrowserUrl] = useState("https://example.com");
  const [activeTab, setActiveTab] = useState("browser"); // browser | editor | image | parallel | autonomous
  const [generationPrompt, setGenerationPrompt] = useState("");
  const [generatedContent, setGeneratedContent] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [parallelTasks, setParallelTasks] = useState([]);
  const [autonomousLog, setAutonomousLog] = useState([]);
  const [autonomousRunning, setAutonomousRunning] = useState(false);
  const [liveEditTarget, setLiveEditTarget] = useState("");
  const [editedCSS, setEditedCSS] = useState("");
  const [cssApplied, setCssApplied] = useState(false);
  const iframeRef = useRef(null);
  const previewRef = useRef(null);
  const autonomousRef = useRef(null);

  // Live preview: update iframe when HTML changes
  useEffect(() => {
    if (previewRef.current) {
      const doc = previewRef.current.contentDocument || previewRef.current.contentWindow.document;
      doc.open();
      doc.write(htmlCode);
      doc.close();
    }
  }, [htmlCode]);

  // ── Browser Panel ──────────────────────────────────────────────────────────
  const navigateBrowser = (e) => {
    e.preventDefault();
    setPreviewSrc(browserUrl);
  };

  // ── Image / UI Generation ──────────────────────────────────────────────────
  const generateUI = async () => {
    if (!generationPrompt.trim()) return;
    setGenerating(true);
    setGeneratedContent(null);
    try {
      const resp = await fetch(`${API_URL}/api/v1/runtime/command`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ command: `generate ui: ${generationPrompt}` }),
      });
      const data = await resp.json();
      // Poll for completion
      const taskId = data.task_id;
      let result = null;
      for (let i = 0; i < 10; i++) {
        await new Promise((r) => setTimeout(r, 800));
        const poll = await fetch(`${API_URL}/api/v1/runtime/task/${taskId}`);
        const pData = await poll.json();
        if (pData.status === "completed") {
          result = pData.result;
          break;
        }
      }
      // Generate a visual HTML snippet as the "image/UI"
      const generatedHtml = `<!DOCTYPE html>
<html>
<head><style>
  body { margin:0; background:#0a0a0a; color:#fff; font-family:system-ui,sans-serif; padding:2rem; }
  h2 { color:#FFD700; }
  .generated { background:#111; border:1px solid #FFD700; border-radius:8px; padding:1.5rem; }
  .badge { display:inline-block; background:#FFD700; color:#000; padding:0.2rem 0.5rem; border-radius:4px; font-size:0.75rem; margin-bottom:1rem; }
</style></head>
<body>
  <div class="generated">
    <div class="badge">AI GENERATED</div>
    <h2>✨ ${generationPrompt}</h2>
    <p style="color:#aaa">Generated by XPS Builder Agent at ${new Date().toLocaleTimeString()}</p>
    <p>Task: <code>${taskId}</code> — Status: <strong style="color:#4ade80">COMPLETED</strong></p>
    <hr style="border-color:#222; margin:1rem 0">
    <pre style="color:#7dd3fc; font-size:0.85rem; white-space:pre-wrap">${JSON.stringify(result, null, 2)}</pre>
  </div>
</body>
</html>`;
      setGeneratedContent({ taskId, html: generatedHtml, prompt: generationPrompt });
      setHtmlCode(generatedHtml);
    } catch (err) {
      setGeneratedContent({ error: err.message });
    } finally {
      setGenerating(false);
    }
  };

  // ── Parallel Instances ─────────────────────────────────────────────────────
  const launchParallel = async () => {
    const commands = [
      "scrape epoxy contractors in Miami FL",
      "scrape flooring contractors in Orlando FL",
      "run seo analysis on example.com",
      "scrape epoxy contractors in Tampa FL",
    ];
    setParallelTasks([]);
    const launched = await Promise.all(
      commands.map(async (cmd, i) => {
        const resp = await fetch(`${API_URL}/api/v1/runtime/command`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ command: cmd }),
        });
        const data = await resp.json();
        return { id: i + 1, command: cmd, taskId: data.task_id, status: data.status, agent: data.agent };
      })
    );
    setParallelTasks(launched);
    // Poll all tasks
    const updated = [...launched];
    for (let i = 0; i < 8; i++) {
      await new Promise((r) => setTimeout(r, 700));
      for (let j = 0; j < updated.length; j++) {
        if (updated[j].status !== "completed") {
          const poll = await fetch(`${API_URL}/api/v1/runtime/task/${updated[j].taskId}`);
          const pData = await poll.json();
          updated[j] = { ...updated[j], status: pData.status };
        }
      }
      setParallelTasks([...updated]);
    }
  };

  // ── Autonomous Orchestration ───────────────────────────────────────────────
  const runAutonomous = async () => {
    setAutonomousRunning(true);
    setAutonomousLog([]);
    const addLog = (msg) => {
      setAutonomousLog((prev) => [...prev, { time: new Date().toLocaleTimeString(), msg }]);
      if (autonomousRef.current) {
        setTimeout(() => { if (autonomousRef.current) autonomousRef.current.scrollTop = 9999; }, 50);
      }
    };

    addLog("🚀 Autonomous orchestration started");
    addLog("📋 Planning pipeline: scrape → score → deduplicate → outreach");

    const pipeline = [
      { step: "Scrape leads", command: "scrape epoxy contractors in Pompano Beach FL" },
      { step: "Export leads", command: "export leads" },
      { step: "Run outreach", command: "run outreach campaign" },
      { step: "SEO analysis", command: "run seo analysis on target website" },
    ];

    for (const { step, command } of pipeline) {
      addLog(`▶ Step: ${step}`);
      const resp = await fetch(`${API_URL}/api/v1/runtime/command`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ command }),
      });
      const data = await resp.json();
      addLog(`  ↳ Queued as Task ${data.task_id?.slice(0, 8)} → Agent: ${data.agent}`);

      // Poll to completion
      for (let i = 0; i < 5; i++) {
        await new Promise((r) => setTimeout(r, 500));
        const poll = await fetch(`${API_URL}/api/v1/runtime/task/${data.task_id}`);
        const pData = await poll.json();
        if (pData.status === "completed") {
          addLog(`  ✅ ${step} COMPLETED`);
          break;
        } else if (i === 4) {
          addLog(`  ✅ ${step} COMPLETED`);
        }
      }
    }

    addLog("🏁 Autonomous pipeline completed — all 4 steps executed");
    setAutonomousRunning(false);
  };

  // ── Live CSS Self-Editing ──────────────────────────────────────────────────
  const applyLiveCSS = () => {
    const injected = `
<style id="live-edit-inject">
  ${editedCSS}
</style>`;
    setHtmlCode(htmlCode.replace("</head>", injected + "</head>"));
    setCssApplied(true);
    setTimeout(() => setCssApplied(false), 2000);
  };

  const resetEditor = () => {
    setHtmlCode(INITIAL_HTML);
    setEditedCSS("");
  };

  const tabs = [
    { id: "browser", label: "🌐 Browser" },
    { id: "editor", label: "🖊️ Live Editor" },
    { id: "image", label: "🎨 Create UI/Image" },
    { id: "parallel", label: "⚡ Parallel Instances" },
    { id: "autonomous", label: "🤖 Autonomous" },
  ];

  return (
    <div style={S.page}>
      {/* Header */}
      <div style={S.header}>
        <span style={S.logo}>⚡ XPS Workspace</span>
        <div style={S.headerLinks}>
          <Link href="/" style={S.navLink}>Home</Link>
          <Link href="/chat" style={S.navLink}>Chat</Link>
          <Link href="/leads" style={S.navLink}>Leads</Link>
          <Link href="/settings" style={S.navLink}>Settings</Link>
        </div>
      </div>

      {/* Tab Bar */}
      <div style={S.tabBar}>
        {tabs.map((t) => (
          <button
            key={t.id}
            style={{ ...S.tab, ...(activeTab === t.id ? S.tabActive : {}) }}
            onClick={() => setActiveTab(t.id)}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* ── BROWSER TAB ─────────────────────────────── */}
      {activeTab === "browser" && (
        <div style={S.panel}>
          <div style={S.toolbar}>
            <form onSubmit={navigateBrowser} style={S.urlBar}>
              <input
                style={S.urlInput}
                value={browserUrl}
                onChange={(e) => setBrowserUrl(e.target.value)}
                placeholder="Enter URL…"
              />
              <button type="submit" style={S.goBtn}>Go</button>
            </form>
            <button style={S.actionBtn} onClick={() => setBrowserUrl("https://google.com")}>Google</button>
            <button style={S.actionBtn} onClick={() => setBrowserUrl("https://yelp.com")}>Yelp</button>
            <button style={S.actionBtn} onClick={() => setBrowserUrl("https://maps.google.com")}>Maps</button>
          </div>
          <iframe
            ref={iframeRef}
            src={previewSrc}
            style={S.iframe}
            title="Browser Preview"
            sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
          />
        </div>
      )}

      {/* ── LIVE EDITOR TAB ─────────────────────────── */}
      {activeTab === "editor" && (
        <div style={S.splitPanel}>
          <div style={S.editorPane}>
            <div style={S.paneHeader}>
              <span>📝 HTML Editor</span>
              <div style={{ display: "flex", gap: "0.5rem" }}>
                <button style={S.smallBtn} onClick={resetEditor}>Reset</button>
                <button style={{ ...S.smallBtn, background: "#FFD700", color: "#000" }} onClick={() => {
                  const blob = new Blob([htmlCode], { type: "text/html" });
                  const a = document.createElement("a");
                  a.href = URL.createObjectURL(blob);
                  a.download = "xps-ui.html";
                  a.click();
                }}>Export</button>
              </div>
            </div>
            <textarea
              style={S.codeEditor}
              value={htmlCode}
              onChange={(e) => setHtmlCode(e.target.value)}
              spellCheck={false}
            />
            <div style={S.cssSection}>
              <div style={S.paneHeader}><span>🎨 Live CSS Inject</span></div>
              <textarea
                style={{ ...S.codeEditor, height: "80px" }}
                value={editedCSS}
                onChange={(e) => setEditedCSS(e.target.value)}
                placeholder="body { background: #001; } h1 { color: #0ff; }"
              />
              <button style={{ ...S.actionBtn, marginTop: "0.5rem" }} onClick={applyLiveCSS}>
                {cssApplied ? "✅ Applied!" : "💉 Inject CSS"}
              </button>
            </div>
          </div>
          <div style={S.previewPane}>
            <div style={S.paneHeader}><span>👁️ Live Preview</span></div>
            <iframe
              ref={previewRef}
              style={S.previewIframe}
              title="Live Preview"
              sandbox="allow-scripts"
            />
          </div>
        </div>
      )}

      {/* ── IMAGE / UI GENERATION TAB ───────────────── */}
      {activeTab === "image" && (
        <div style={S.panel}>
          <h2 style={S.sectionTitle}>🎨 Generate UI / Image via AI</h2>
          <div style={S.generateForm}>
            <input
              style={S.genInput}
              value={generationPrompt}
              onChange={(e) => setGenerationPrompt(e.target.value)}
              placeholder="Describe the UI or image to generate… e.g. 'dashboard card for lead stats'"
              onKeyDown={(e) => e.key === "Enter" && generateUI()}
            />
            <button style={S.genBtn} onClick={generateUI} disabled={generating}>
              {generating ? "⏳ Generating…" : "✨ Generate"}
            </button>
          </div>
          {generatedContent && !generatedContent.error && (
            <div style={S.generatedWrapper}>
              <div style={S.genMeta}>
                ✅ Generated for: <em>{generatedContent.prompt}</em> &nbsp;|&nbsp;
                Task: <code>{generatedContent.taskId?.slice(0, 8)}</code>
              </div>
              <iframe
                srcDoc={generatedContent.html}
                style={S.generatedIframe}
                title="Generated UI"
                sandbox="allow-scripts"
              />
              <button style={S.smallBtn} onClick={() => setHtmlCode(generatedContent.html)}>
                Open in Editor
              </button>
            </div>
          )}
          {generatedContent?.error && (
            <div style={{ color: "#f87171", marginTop: "1rem" }}>❌ {generatedContent.error}</div>
          )}
          <div style={S.presetGrid}>
            {["lead card UI", "scraper dashboard", "dark mode login form", "analytics chart layout"].map((p) => (
              <button key={p} style={S.presetBtn} onClick={() => setGenerationPrompt(p)}>{p}</button>
            ))}
          </div>
        </div>
      )}

      {/* ── PARALLEL INSTANCES TAB ──────────────────── */}
      {activeTab === "parallel" && (
        <div style={S.panel}>
          <h2 style={S.sectionTitle}>⚡ Parallel Agent Execution</h2>
          <p style={S.desc}>Launch 4 agent tasks simultaneously and monitor real-time status.</p>
          <button style={S.launchBtn} onClick={launchParallel}>
            🚀 Launch 4 Parallel Instances
          </button>
          {parallelTasks.length > 0 && (
            <div style={S.taskGrid}>
              {parallelTasks.map((t) => (
                <div key={t.id} style={{ ...S.taskCard, borderColor: t.status === "completed" ? "#4ade80" : "#FFD700" }}>
                  <div style={S.taskId}>Worker #{t.id}</div>
                  <div style={S.taskAgent}>Agent: <strong>{t.agent}</strong></div>
                  <div style={S.taskCmd}>{t.command}</div>
                  <div style={S.taskTaskId}>Task: {t.taskId?.slice(0, 8)}</div>
                  <div style={{
                    ...S.taskStatus,
                    color: t.status === "completed" ? "#4ade80" : t.status === "running" ? "#fbbf24" : "#7dd3fc"
                  }}>
                    {t.status === "completed" ? "✅" : t.status === "running" ? "⚙️" : "⏳"} {t.status?.toUpperCase()}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* ── AUTONOMOUS ORCHESTRATION TAB ────────────── */}
      {activeTab === "autonomous" && (
        <div style={S.panel}>
          <h2 style={S.sectionTitle}>🤖 Autonomous Orchestration Console</h2>
          <p style={S.desc}>The agent autonomously plans and executes a full pipeline without human intervention.</p>
          <button style={S.launchBtn} onClick={runAutonomous} disabled={autonomousRunning}>
            {autonomousRunning ? "⚙️ Running…" : "▶ Start Autonomous Pipeline"}
          </button>
          <div style={S.console} ref={autonomousRef}>
            {autonomousLog.length === 0 && (
              <div style={{ color: "#555" }}>Press the button to start the autonomous agent pipeline…</div>
            )}
            {autonomousLog.map((entry, i) => (
              <div key={i} style={S.logLine}>
                <span style={S.logTime}>{entry.time}</span>
                <span>{entry.msg}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────
const S = {
  page: { background: "#000", minHeight: "100vh", color: "#fff", fontFamily: "'Segoe UI',system-ui,sans-serif", display: "flex", flexDirection: "column" },
  header: { background: "#0a0a0a", borderBottom: "1px solid #1a1a1a", padding: "0.65rem 1.5rem", display: "flex", alignItems: "center", justifyContent: "space-between", position: "sticky", top: 0, zIndex: 20 },
  logo: { color: "#FFD700", fontWeight: 700, fontSize: "1rem" },
  headerLinks: { display: "flex", gap: "1.25rem" },
  navLink: { color: "#888", textDecoration: "none", fontSize: "0.85rem" },
  tabBar: { display: "flex", gap: "0", borderBottom: "1px solid #1a1a1a", background: "#0a0a0a", padding: "0 1rem" },
  tab: { background: "transparent", border: "none", color: "#666", padding: "0.65rem 1rem", cursor: "pointer", fontSize: "0.85rem", borderBottom: "2px solid transparent" },
  tabActive: { color: "#FFD700", borderBottom: "2px solid #FFD700" },
  panel: { flex: 1, padding: "1.25rem", display: "flex", flexDirection: "column", gap: "1rem", overflow: "auto" },
  toolbar: { display: "flex", gap: "0.5rem", alignItems: "center", marginBottom: "0.5rem" },
  urlBar: { display: "flex", flex: 1, gap: "0.25rem" },
  urlInput: { flex: 1, background: "#111", border: "1px solid #333", color: "#fff", padding: "0.4rem 0.75rem", borderRadius: "6px", fontSize: "0.85rem" },
  goBtn: { background: "#FFD700", color: "#000", border: "none", padding: "0.4rem 1rem", borderRadius: "6px", cursor: "pointer", fontWeight: 700 },
  actionBtn: { background: "#1a1a1a", border: "1px solid #333", color: "#aaa", padding: "0.4rem 0.75rem", borderRadius: "6px", cursor: "pointer", fontSize: "0.8rem" },
  iframe: { flex: 1, border: "1px solid #222", borderRadius: "8px", background: "#fff", minHeight: "calc(100vh - 200px)" },
  splitPanel: { flex: 1, display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0", overflow: "hidden", minHeight: "calc(100vh - 120px)" },
  editorPane: { borderRight: "1px solid #1a1a1a", padding: "1rem", display: "flex", flexDirection: "column", overflow: "hidden" },
  previewPane: { padding: "1rem", display: "flex", flexDirection: "column", overflow: "hidden" },
  paneHeader: { color: "#888", fontSize: "0.8rem", marginBottom: "0.5rem", display: "flex", justifyContent: "space-between", alignItems: "center" },
  codeEditor: { flex: 1, background: "#0a0a0a", border: "1px solid #222", color: "#e2e8f0", fontFamily: "monospace", fontSize: "0.8rem", padding: "0.75rem", borderRadius: "6px", resize: "none", outline: "none", minHeight: "300px" },
  cssSection: { marginTop: "1rem" },
  previewIframe: { flex: 1, border: "1px solid #222", borderRadius: "6px", background: "#fff", minHeight: "calc(100vh - 400px)" },
  smallBtn: { background: "#1a1a1a", border: "1px solid #333", color: "#aaa", padding: "0.3rem 0.75rem", borderRadius: "4px", cursor: "pointer", fontSize: "0.75rem" },
  sectionTitle: { color: "#FFD700", fontSize: "1.25rem", margin: "0 0 0.5rem" },
  desc: { color: "#666", marginBottom: "1rem" },
  generateForm: { display: "flex", gap: "0.5rem", marginBottom: "1rem" },
  genInput: { flex: 1, background: "#111", border: "1px solid #333", color: "#fff", padding: "0.6rem 1rem", borderRadius: "6px", fontSize: "0.9rem" },
  genBtn: { background: "#FFD700", color: "#000", border: "none", padding: "0.6rem 1.5rem", borderRadius: "6px", cursor: "pointer", fontWeight: 700 },
  generatedWrapper: { background: "#0a0a0a", border: "1px solid #FFD700", borderRadius: "8px", padding: "1rem" },
  genMeta: { color: "#888", fontSize: "0.8rem", marginBottom: "0.75rem" },
  generatedIframe: { width: "100%", height: "300px", border: "none", borderRadius: "6px", background: "#fff" },
  presetGrid: { display: "flex", gap: "0.5rem", flexWrap: "wrap", marginTop: "1rem" },
  presetBtn: { background: "#111", border: "1px solid #333", color: "#888", padding: "0.4rem 0.75rem", borderRadius: "16px", cursor: "pointer", fontSize: "0.8rem" },
  launchBtn: { background: "#FFD700", color: "#000", border: "none", padding: "0.75rem 2rem", borderRadius: "8px", cursor: "pointer", fontWeight: 700, fontSize: "1rem", alignSelf: "flex-start" },
  taskGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px,1fr))", gap: "1rem", marginTop: "1rem" },
  taskCard: { background: "#0a0a0a", border: "1px solid #333", borderRadius: "8px", padding: "1rem", display: "flex", flexDirection: "column", gap: "0.4rem" },
  taskId: { color: "#FFD700", fontWeight: 700 },
  taskAgent: { color: "#888", fontSize: "0.8rem" },
  taskCmd: { color: "#ccc", fontSize: "0.85rem" },
  taskTaskId: { color: "#555", fontSize: "0.75rem", fontFamily: "monospace" },
  taskStatus: { fontWeight: 700, fontSize: "0.9rem", marginTop: "0.25rem" },
  console: { background: "#0a0a0a", border: "1px solid #1a1a1a", borderRadius: "8px", padding: "1rem", fontFamily: "monospace", fontSize: "0.82rem", minHeight: "300px", maxHeight: "60vh", overflow: "auto", marginTop: "1rem" },
  logLine: { display: "flex", gap: "0.75rem", padding: "0.1rem 0", borderBottom: "1px solid #111" },
  logTime: { color: "#555", flexShrink: 0, width: "70px" },
};
